import axios from "axios";

export const FIREBASE_URL =
  "https://expenssio-default-rtdb.asia-southeast1.firebasedatabase.app/";

export async function storeExpense(expenseData) {
  const response = await axios.post(
    `${FIREBASE_URL}/expenses.json`,
    expenseData
  );

  const id = response.data.name;
  return id;
}

export async function fetchExpenses() {
  const response = await axios.get(`${FIREBASE_URL}/expenses.json`);

  const expenses = [];

  for (const key in response.data) {
    const expenseObj = {
      id: key, //this key is generated by firebase and stored as id which is a hashed string
      amount: response.data[key].amount,
      date: new Date(response.data[key].date),
      description: response.data[key].description,
    };
    expenses.push(expenseObj);
  }

  return expenses;
}

export function updateExpense(editedExpenseId, expenseData) {
  return axios.put(
    `${FIREBASE_URL}/expenses/${editedExpenseId}.json`,
    expenseData
  );
}

export function deleteExpense(editedExpenseId) {
  return axios.delete(`${FIREBASE_URL}/expenses/${editedExpenseId}.json`);
}
